name: app
publish_to: "none"
version: 1.0.5+6

environment:
  sdk: ">=2.8.0 <3.0.0" # DART SDK VERSION
  # flutter: "" # FLUTTER SDK VERSION

dependencies:
  flutter:
    sdk: flutter

  #UTILS
  get: 4.3.8
  hive: 2.0.4
  hive_flutter: 1.1.0
  url_launcher: 6.0.9
  timeago: 3.1.0
  logger: 1.0.0
  intl: 0.17.0
  supercharged: 2.0.0
  either_option: 1.0.6
  #INFO
  device_info: 2.0.2
  package_info: 2.0.2
  #MEDIA
  cached_network_image: 3.1.0
  flutter_spinkit: 5.0.0
  flutter_icons: 1.1.0
  #NETWORK
  dio: 4.0.0
  connectivity: 3.0.6
  #UI
  flutter_staggered_animations: 1.0.0
  flutter_easyrefresh: 2.2.1
  bubble_tab_indicator: 0.1.6
  flutter_linkify: 5.0.2
  shimmer: 2.0.0
  step_progress_indicator: 1.0.1

# DEVELOPER DEPENDENCIES
dev_dependencies:
  build_runner: 2.1.1
  flutter_launcher_icons: 0.9.1
  hive_generator: 1.1.0
  flutter_native_splash: 1.2.1

# SPLASH SCREEN GENERATOR
flutter_native_splash:
  image: assets/images/splash.png
  color: "000000"

# ICON GENERATOR
flutter_icons:
  android: "ic_launcher"
  image_path_android: "assets/images/app_icon.png"
  ios: true
  image_path_ios: "assets/images/app_icon.png"

# FLUTTER SETTINGS
flutter:
  uses-material-design: true

  # ASSETS / FILES
  assets:
    # GENERIC IMAGE ASSETS
    - assets/
    - assets/images/
