name: app
publish_to: "none"
version: 1.0.7+8

environment:
  sdk: ">=2.8.0 <3.0.0" # DART SDK VERSION
  # flutter: "" # FLUTTER SDK VERSION

dependencies:
  flutter:
    sdk: flutter

  #UTILS
  get: 4.6.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  url_launcher: 6.1.7
  timeago: 3.3.0
  logger: 1.1.0
  intl: 0.17.0
  supercharged: 2.1.1
  either_option: 2.0.0
  #INFO
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  #MEDIA
  cached_network_image: 3.2.3
  flutter_spinkit: 5.1.0
  flutter_icons: 1.1.0
  #NETWORK
  dio: 4.0.6
  connectivity_plus: ^3.0.2
  #UI
  flutter_staggered_animations: 1.1.1
  flutter_easyrefresh: 2.2.2
  bubble_tab_indicator: 0.1.6
  flutter_linkify: 5.0.2
  shimmer: 2.0.0
  step_progress_indicator: 1.0.2
  locale_emoji_flutter: ^0.2.1
  emoji_flag_converter: ^1.1.0

# DEVELOPER DEPENDENCIES
dev_dependencies:
  build_runner: 2.3.3
  flutter_launcher_icons: 0.11.0
  hive_generator: 2.0.0
  flutter_native_splash: 2.2.16
  flutter_lints: ^2.0.1

# SPLASH SCREEN GENERATOR
flutter_native_splash:
  image: assets/images/splash.png
  color: "000000"

# ICON GENERATOR
flutter_icons:
  android: "ic_launcher"
  image_path_android: "assets/images/app_icon.png"
  ios: true
  image_path_ios: "assets/images/app_icon.png"

# FLUTTER SETTINGS
flutter:
  uses-material-design: true

  # ASSETS / FILES
  assets:
    # GENERIC IMAGE ASSETS
    - assets/
    - assets/images/
