name: app
publish_to: "none"
version: 1.0.5+6

environment:
  sdk: ">=2.8.0 <3.0.0" # DART SDK VERSION
  # flutter: "" # FLUTTER SDK VERSION

dependencies:
  flutter:
    sdk: flutter

  #UTILS
  get: 3.24.0
  hive: 1.4.4+1
  hive_flutter: 0.3.1
  url_launcher: 5.7.10
  timeago: 2.0.29
  logger: 0.9.4
  intl: 0.16.1
  supercharged: 1.12.0
  either_option: 1.0.6
  #INFO
  device_info: 1.0.0
  package_info: 0.4.3+4
  #MEDIA
  cached_network_image: 2.5.0
  flutter_spinkit: 4.1.2+1
  flutter_icons: 1.1.0
  #NETWORK
  dio: 3.0.10
  connectivity: 2.0.2
  #UI
  flutter_staggered_animations: 0.1.2
  flutter_easyrefresh: 2.1.8
  bubble_tab_indicator: 0.1.4
  flutter_linkify: 4.0.2
  shimmer: 1.1.2
  step_progress_indicator: 0.2.5+8

# DEVELOPER DEPENDENCIES
dev_dependencies:
  build_runner: 1.11.0
  flutter_launcher_icons: 0.8.1
  hive_generator: 0.8.2
  flutter_native_splash: 0.2.9

# SPLASH SCREEN GENERATOR
flutter_native_splash:
  image: assets/images/splash.png
  color: "000000"

# ICON GENERATOR
flutter_icons:
  android: "ic_launcher"
  image_path_android: "assets/images/app_icon.png"
  ios: true
  image_path_ios: "assets/images/app_icon.png"

# FLUTTER SETTINGS
flutter:
  uses-material-design: true

  # ASSETS / FILES
  assets:
    # GENERIC IMAGE ASSETS
    - assets/
    - assets/images/
